### ISSUE TITLE
Scraper automation

### ISSUE THREAD

**Issue by Be1zebub** [WilliamVenner/vscode-glua-enhanced#64]
The wiki scrape seems to be outdated, its worth automating this work.  
I've sketched out a small action for this, I hope it will be useful.  

```yaml
name: Wiki Scraper 

on:
  workflow_dispatch: # manual
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  scrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Scraper 
        run: python generator/main.py

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resources/wiki.json
          git commit -m "Wiki scraper"

      - name: Push changes
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
```
